### PR TITLE
Fix race condition when block is found and share record is not yet at th...

### PR DESCRIPTION
**Pull request by svasva**
...e DB

I'm not sure sleep is a good solution for that, but it works.
Without it, I'm having an issue where on high load (> 500mh/s) some blocks aren't going into database.

### CODE REVIEW

**Comment by obigal** [comment]
Not sure if this is the same issue I'm having or what your front end your even using but theserapher alluded to it here
https://github.com/moopless/stratum-mining-litecoin/issues/35
and that's exactly what is going on on a pool of mine the shares get into the db out of order and the missing 'Y' gets swept into the archive messing up the block and shares ordering I have set the DB_LOADER_REC_MIN and MAX to 1 and that pool has stopped missing shares but it hasn't had quite the hash power right now as it did when it was happening but has seemed to cure the issue for now.

```
DB_LOADER_REC_MIN = 1      # Min Records before the bulk loader fires
DB_LOADER_REC_MAX = 1      # Max Records the bulk loader will commit at a time
```

**Comment by svasva** [comment]
setting it to commit each share is not an option as the server load would skyrocket with that setting :(

**Comment by obigal** [comment]
I thought the same thing as well but haven't seen no real ill effects (but mines only about 50Mhs), a pushpool server would enter them the same way 1 by 1 or even viperaus stratum so couldn't hurt to try.

**Comment by svasva** [comment]
My pool is getting 2k shares per minute (running at ~700mh/s), and that's not the only pool on that server thus mysql having a hard time already.
So dumping shares instantly to the database would be a pain...

**Comment by obigal** [comment]
I'm going to try it see what happens, hope it works!

**Comment by obigal** [comment]
Unfortunately this doesn't fix my issue ;(

**Comment by moopless** [comment]
Hmm this is an interesting one. I'll look through the code to see what can be done. Maybe a simple change would be to flush the queue when a block is found. That way we make sure the share is in the db. 

We can also do an insert if there is no share record found. It may result in an extra share in the database on special edge cases. 

Someone deleted all of my dev servers, so it will be a day or two until I can get back up and running to make these changes.

**Comment by moopless** [comment]
After thinking about this for a few minutes, I think we need to flush the queue when the block is found. Once the queue has been flushed we can update the correct share, or if the share is not found we need to insert it because there is nothing sitting in the queue. It should not cause an extra share to be in the database.

**Comment by svasva** [comment]
wasn't this code supposed to dump shares into the DB before updating upstream_result?
it doesn't help much though :(
(DBInterface.py)

``` python
            self.do_import(self.dbi, True)  # We can't Update if the record is not there.
            self.dbi.found_block(data)
```

**Comment by svasva** [comment]
@moopless let me know if you need some spare servers to test that stuff. i can fire up a VPS for you. another way to contribute to the project, right :)
(you can email me at [my github nickname]@gmail.com)

**Comment by obigal** [comment]
Just a little update, this hasn't really worked for me either, I'm still marking a lot of 'Y' shares

```
DB_LOADER_REC_MIN = 1 
DB_LOADER_REC_MAX = 1
```

**Comment by moopless** [comment]
@erundook You are right. That is already there to force the import before the update. I'll look to see what else can be done.  Thanks for the VPS offer. I should be alright with what I have. Someone accidentally deleted all of mine because they were not labeled correctly.

**Comment by moopless** [comment]
In the logs around this, do you see it force the import? It looks like there is a small logic error when the block is found. Below is the loop for doing the import.

```
 while force == True or self.q.qsize() >= settings.DB_LOADER_REC_MIN or time.time() >= self.next_force_import_time:
```

After the first settings.DB_LOADER_REC_MIN  we set force = False. So if self.q.qsize() < settings.DB_LOADER_REC_MIN, we will not add them in. This could lead to a problem if the block was found in the last settings.DB_LOADER_REC_MIN -1  shares. self.next_force_import_time is set in the loop, so that will not apply either.

So the easy test for this problem is to set DB_LOADER_REC_MIN = 0 in conf/config.py. 

I will also change the update to do an insert if the record does not exist.

**Comment by svasva** [comment]
But it does set the force parameter to True when importing for a new block, so (true || false) code should be executed anyway, right?
As I said before, I can't go without DB cache (DB_LOADER_REC_MIN = 0) as it will make server load skyrocket...

**Comment by moopless** [comment]
Added a small commit. It adds an extra query to each found block. It looks to be working on a cpu miner with testnet. Can anyone else test as well? Make sure to set DB_LOADER_REC_MIN = 0 as per above.

**Comment by feeleep75** [comment]
hi,

why `'%(result)s'` in

```
INSERT INTO shares
+                (time, rem_host, username, our_result, 
+                  upstream_result, reason, solution)
+                VALUES 
+                (FROM_UNIXTIME(%(time)s), %(host)s, 
+                  %(uname)s, 
+                  %(lres)s, '%(result)s', %(reason)s, %(solution)s)
```

is in quotes?

**Comment by moopless** [comment]
Because I was way too tired when I ported it over this morning. I'll
remediate that.

**Comment by moopless** [comment]
@erundook force gets set to False on the first run. Setting DB_LOADER_REC_MIN to 0 should not fully disable the queuing, but rather flush the whole queue every time do_import is called. 

I found another way to go about it. I can change the behavior of force, so that it flushes the whole queue. It is kind of ugly in the code, but should work.

**Comment by moopless** [comment]
28 blocks found on testnet with no issues with 0d78269. Force flushes seem to be working as well. The code is ugly, but it should work.

**Comment by svasva** [comment]
okay i've updated my live pool to this code, will see if it helps. also updated queue min size to 1, as 0 makes it loop forever inserting 0 shares

**Comment by moopless** [comment]
@erundook Sounds good. Let me know how it goes.

**Comment by TheSerapher** [comment]
I also see that 0 shares inserted issue.

**Comment by svasva** [comment]
@TheSerapher I guess that's obvious that it is going into a forever loop while checking if it has to insert something. You'll need that value to be set to at least one share to prevent that :)

**Comment by moopless** [comment]
I should have checked that. If we set it to 0, we need to get rid of the = in the while loop. 

```
self.q.qsize() >= settings.DB_LOADER_REC_MIN
```

Should be:

```
self.q.qsize() > settings.DB_LOADER_REC_MIN
```

**Comment by moopless** [comment]
Actually It would be better to do the following to allow DB_LOADER_REC_MIN = 0.

```
 while force == True or (self.q.qsize() >= settings.DB_LOADER_REC_MIN and self.q.qsize() != 0) or time.time() >= self.next_force_import_time:
```

**Comment by svasva** [comment]
Awesome, no missed blocks so far. I will check again next morning and if its still okay we should consider this resolved. Thanks @moopless !

**Comment by TheSerapher** [comment]
Don't have the config at hand but it was the default from master branch.

**Comment by svasva** [comment]
@TheSerapher yep it should be fixed with that last commit @moopless did.

**Comment by TheSerapher** [comment]
Will this also fix #35?

**Comment by moopless** [comment]
@TheSerapher It should fix missing block shares in the database. It may fix #35. I have to investigate that issue, but I don't have the hashing power to reproduce it.

**Comment by svasva** [comment]
@moopless you could just set pool target diff to 1 and switch VARDIFF off so you will produce alot of shares :)

**Comment by svasva** [comment]
those last commits lead to infinite loop inserting 0 shares at random times somehow...

**Comment by svasva** [comment]
and what's that? never noticed it before

```
2013-07-16 22:51:35,602 INFO template_registry # New template for 2d91c570f86aef85d2dd9245539dbce493da935befc419dcc11d2aa502e69103
2013-07-16 22:51:35,612 ERROR template_registry # [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'write'
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:1126:gotResult
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:1113:_inlineCallbacks
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:380:callback
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:488:_startRunCallbacks
--- <exception caught here> ---
/usr/local/lib/python2.7/dist-packages/Twisted-13.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py:575:_runCallbacks
/home/erundook/dgc/poolfe/stratum/lib/template_registry.py:133:_update_block
/home/erundook/dgc/poolfe/stratum/lib/template_registry.py:103:add_template
/home/erundook/dgc/poolfe/stratum/mining/subscription.py:26:on_template
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/pubsub.py:54:emit
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/pubsub.py:160:emit
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/pubsub.py:66:emit_single
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:102:writeJsonRequest
/usr/local/lib/python2.7/dist-packages/stratum-0.2.12-py2.7.egg/stratum/protocol.py:83:transport_write
]
```

**Comment by obigal** [comment]
I've looked at this over and over again and still can't quite figure out what it tries to accomplish, isn't this the same thing as setting min to 1?

**Comment by moopless** [comment]
@obigal You are correct. Setting DB_LOADER_REC_MIN = 0 should accomplish the same thing as DB_LOADER_REC_MIN = 1. I must have been pretty tired when I changed it that morning. I reverted that setting yesterday in the configs. The purpose of these changes are to allow you to have DB_LOADER_REC_MIN = x, where x >1 and still not see an issue where the correct shares are not put into the database.

The second change made was an insert on a missing share. So even if the share is missing after the queue was emptied on the block submit, we will insert it as the block share.

@erundook Are you seeing the infinite loop with DB_LOADER_MIN >= 1? Let's track the traceback in another issue.

**Comment by svasva** [comment]
@moopless yes, it is = 1 in my config, but after some time it still goes into infinite loop inserting 0 shares. And there  is no traceback I could get :(

**Comment by svasva** [comment]
Actually that made my pool down for some hours since i've updated to this code, checked it was working and went to bed. And found it stuck in that loop when I got up :(

**Comment by svasva** [comment]
looks like this:

```
2013-07-17 13:13:16,725 INFO subscription # BROADCASTED to 264 connections in 0.017 sec
2013-07-17 13:13:16,725 INFO template_registry # Update finished, 0.018 sec, 1 txes
2013-07-17 13:13:16,753 INFO BasicShareLimiter # Checking Retarget for BigDaddyWooWoo.4 (68) avg. 9 target 15+-3
2013-07-17 13:13:16,753 INFO BasicShareLimiter # Retarget for BigDaddyWooWoo.4 45 old: 68 new: 114
2013-07-17 13:13:16,757 INFO interfaces # 000000b3fd8da8b343dba8a555fdc629d92b7495d624ac1d059edc937e9c4219 (364) valid BigDaddyWooWoo.4
2013-07-17 13:13:16,791 INFO interfaces # 0000006ec7ae40235a4a8f388510837da8728c92081884644cd1a3702d28ee7a (591) valid stevenlam.2
2013-07-17 13:13:16,811 INFO interfaces # 00000122a3314d9fe5ccdd72bb65f5f8852a8c83f01c9cef08c1d9491cfc4164 (225) valid picbb1.1
2013-07-17 13:13:16,824 INFO interfaces # 0000000fda36399fac14ed655afbcc426f13de6d1dfe3bdeedd81d4362e33ed8 (4134) valid vampirevn.13
2013-07-17 13:13:16,825 INFO BasicShareLimiter # Checking Retarget for vmnet.a (202) avg. 13 target 15+-3
2013-07-17 13:13:16,828 INFO interfaces # 000000b002764eb852fa8aa90ccdc50e9de2a21dfb4a7cd9a10e489662e82d6f (372) valid vmnet.a
2013-07-17 13:13:16,837 INFO DBInterface # Inserting 50 Share Records
2013-07-17 13:13:16,878 INFO interfaces # 0000004b759b6ccaecf90d3e7c011b111ec8e847c099c5a6df2c06395e235375 (868) valid avb68.48cf
2013-07-17 13:13:16,882 INFO interfaces # 00000368f49e3f615497434f86e1d6e6de16d57417acd659f72b93552c2b60a9 (75) valid BigDaddyWooWoo.5
2013-07-17 13:13:16,904 INFO DBInterface # Inserting 50 Share Records
2013-07-17 13:13:16,928 INFO interfaces # Block 000000002d4b215eaf9d03c56a1fd3b529e45fd92345efc26f70aadd49b74914 ACCEPTED
2013-07-17 13:13:16,928 INFO DBInterface # Updating Found Block Share Record
2013-07-17 13:13:16,929 INFO DBInterface # Inserting 50 Share Records
2013-07-17 13:13:16,980 INFO DBInterface # Inserting 50 Share Records
2013-07-17 13:13:16,991 INFO DBInterface # Inserting 31 Share Records
2013-07-17 13:13:17,047 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,047 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,047 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,047 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,048 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,048 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,048 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,048 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,048 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,049 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,049 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,049 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,049 INFO DBInterface # Inserting 0 Share Records
2013-07-17 13:13:17,049 INFO DBInterface # Inserting 0 Share Records
```

**Comment by svasva** [comment]
and goes stuck forever

**Comment by moopless** [comment]
@erundook The stack trace issue is now tracked in #38 for what was seen in https://github.com/moopless/stratum-mining-litecoin/pull/37#issuecomment-21080200 

There has to be a logic error in there for it to hit that infinite loop. I changed the while loop logic to the following.

```
while self.q.empty() == False and (force == True or self.q.qsize() >= settings.DB_LOADER_REC_MIN or time.time() >= self.next_force_import_time or forcesize > 0):
```

So we should not stick in the while loop if the queue is empty. I am testing this now.

**Comment by moopless** [comment]
For reference, When I run these tests for this I am submitting about 1500 shares every 15 seconds, so about 100 shares per second on average. The database dump takes about 1.2 seconds to dump the 1500 shares every time we call _do_import_. I'll let it run for another few hours and push the change.

**Comment by moopless** [comment]
Pushed 877a228 as I have not seen any issues with it over the last few hours.

**Comment by svasva** [comment]
i think this can be considered as resolved as well.
thanks @moopless !

**Comment by moopless** [comment]
@erundook Thank you for working with me on this. Sorry for the issue with the loop last night. I will try to run the test longer before pushing them. 

Since this issue is closed, I'll merge it into the main branch

**Pull request closed without merging**
